# Generated by Django 5.1.15 on 2026-06-11 21:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "tag",
                    models.CharField(blank=True, max_length=40, verbose_name="Tag (chip w hero)"),
                ),
                ("hero_lead", models.TextField(blank=True, verbose_name="Lead w hero")),
                (
                    "primary_cta_label",
                    models.CharField(blank=True, max_length=60, verbose_name="CTA główne — tekst"),
                ),
                (
                    "primary_cta_url",
                    models.CharField(blank=True, max_length=255, verbose_name="CTA główne — URL"),
                ),
                (
                    "secondary_cta_label",
                    models.CharField(blank=True, max_length=60, verbose_name="CTA drugie — tekst"),
                ),
                (
                    "secondary_cta_url",
                    models.CharField(blank=True, max_length=255, verbose_name="CTA drugie — URL"),
                ),
                (
                    "hero_box_chip",
                    models.CharField(blank=True, max_length=40, verbose_name="Box hero — etykieta"),
                ),
                (
                    "hero_box_heading",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Box hero — nagłówek"
                    ),
                ),
                (
                    "hero_box_items",
                    models.TextField(
                        blank=True, verbose_name="Box hero — pozycje (jedna na linię)"
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True, verbose_name="Opis usługi")),
                (
                    "benefits_heading",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Nagłówek sekcji korzyści"
                    ),
                ),
                (
                    "process_heading",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Nagłówek sekcji procesu"
                    ),
                ),
                (
                    "pricing",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Cennik / widełki"),
                ),
                (
                    "faq_heading",
                    models.CharField(
                        blank=True,
                        default="Najczęściej zadawane pytania.",
                        max_length=160,
                        verbose_name="Nagłówek sekcji FAQ",
                    ),
                ),
                (
                    "cta_heading",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="CTA strip — nagłówek"
                    ),
                ),
                ("cta_lead", models.TextField(blank=True, verbose_name="CTA strip — lead")),
                (
                    "cta_button_label",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="CTA strip — przycisk"
                    ),
                ),
                (
                    "cta_button_url",
                    models.CharField(blank=True, max_length=255, verbose_name="CTA strip — URL"),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obraz pokazywany przy udostępnianiu na FB/LinkedIn. Zalecane 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Obraz social (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usługa",
                "verbose_name_plural": "Usługi",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="ServiceFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("question", models.CharField(max_length=255, verbose_name="Pytanie")),
                ("answer", wagtail.fields.RichTextField(verbose_name="Odpowiedź")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="services.servicepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("tag", models.CharField(blank=True, max_length=40, verbose_name="Tag")),
                ("title", models.CharField(max_length=160, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="services.servicepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServicesIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True, default="Usługi klastra", max_length=80, verbose_name="Nadtytuł"
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True, verbose_name="Wstęp")),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obraz pokazywany przy udostępnianiu na FB/LinkedIn. Zalecane 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Obraz social (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Katalog usług",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="ServiceStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "number",
                    models.CharField(help_text="np. '01'", max_length=4, verbose_name="Numer"),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="services.servicepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
