# Generated by Django 5.1.15 on 2026-06-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nazwa")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Slug")),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("recykling", "Recykling"),
                            ("produkcja", "Produkcja"),
                            ("technologie", "Technologie"),
                            ("nauka", "Nauka"),
                            ("doradztwo", "Doradztwo"),
                            ("finanse", "Finanse"),
                            ("administracja", "Administracja"),
                        ],
                        default="recykling",
                        max_length=20,
                        verbose_name="Sektor",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                ("website", models.URLField(blank=True, verbose_name="Strona WWW")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Wyróżniony")),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Członek",
                "verbose_name_plural": "Członkowie",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nazwa")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("instytucja", "Instytucja publiczna"),
                            ("uczelnia", "Uczelnia / jednostka naukowa"),
                            ("klaster_ue", "Klaster partnerski w UE"),
                            ("branzowy", "Partner branżowy"),
                        ],
                        default="instytucja",
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="Link")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Kolejność")),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partnerzy",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Imię i nazwisko")),
                ("role", models.CharField(blank=True, max_length=160, verbose_name="Rola")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("zarzad", "Zarząd i koordynator"),
                            ("biuro", "Biuro klastra"),
                            ("rada", "Rada klastra"),
                        ],
                        default="biuro",
                        max_length=20,
                        verbose_name="Grupa",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-mail")),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Kolejność")),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Osoba zespołu",
                "verbose_name_plural": "Zespół",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
