# Generated by Django 5.1.15 on 2026-06-12 07:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembersIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(blank=True, default="Społeczność klastra", max_length=80),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True, verbose_name="Wstęp")),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obraz pokazywany przy udostępnianiu na FB/LinkedIn. Zalecane 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Obraz social (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista członków",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="PartnersPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True, verbose_name="Wstęp")),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obraz pokazywany przy udostępnianiu na FB/LinkedIn. Zalecane 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Obraz social (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partnerzy",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="TeamPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True, verbose_name="Wstęp")),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obraz pokazywany przy udostępnianiu na FB/LinkedIn. Zalecane 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Obraz social (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zespół",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
