# Generated by Django 5.1.15 on 2026-06-12 07:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cluster", "0002_membersindexpage_partnerspage_teampage"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutClusterPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True, default="Krajowy Klaster Kluczowy · od 2012", max_length=120
                    ),
                ),
                ("hero_lead", models.TextField(blank=True, verbose_name="Lead w hero")),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("text_section", 4), ("cards", 10), ("steps", 12)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Nadtytuł", "required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Nagłówek", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link", "ul", "ol"],
                                    "label": "Treść",
                                },
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("none", "Białe"),
                                        ("green", "Zielone"),
                                        ("dark", "Ciemne"),
                                    ],
                                    "label": "Tło",
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("eyebrow", 0), ("heading", 1), ("body", 2), ("background", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Numer", "required": False},
                            ),
                            6: ("wagtail.blocks.CharBlock", (), {"label": "Tytuł"}),
                            7: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Opis", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("number", 5), ("title", 6), ("text", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.ListBlock", (8,), {"label": "Karty"}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("eyebrow", 0), ("heading", 1), ("cards", 9), ("background", 3)]],
                                {},
                            ),
                            11: ("wagtail.blocks.ListBlock", (8,), {"label": "Kroki"}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("heading", 1),
                                        ("steps", 11),
                                        ("background", 3),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Sekcje strony O klastrze.",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obraz pokazywany przy udostępnianiu na FB/LinkedIn. Zalecane 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Obraz social (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "O klastrze",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
