# Generated by Django 5.1.15 on 2026-06-10 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ga4_measurement_id",
                    models.CharField(
                        blank=True,
                        help_text="np. G-XXXXXXXXXX. Puste = analytics wyłączone.",
                        max_length=20,
                        verbose_name="GA4 Measurement ID",
                    ),
                ),
                (
                    "cookie_banner_text",
                    models.TextField(
                        blank=True,
                        default="Używamy plików cookies do analizy ruchu (Google Analytics). Możesz zaakceptować lub odrzucić.",
                        verbose_name="Treść bannera cookies",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics i cookies",
            },
        ),
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        default="Klaster GOZ", max_length=200, verbose_name="Nazwa organizacji"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=40, verbose_name="Telefon")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="E-mail")),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Może być wieloliniowy.", verbose_name="Adres"
                    ),
                ),
                ("nip", models.CharField(blank=True, max_length=20, verbose_name="NIP")),
                (
                    "footer_description",
                    models.TextField(blank=True, max_length=400, verbose_name="Opis w stopce"),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo w headerze. Puste = domyślne logo z design systemu.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dane ogólne",
            },
        ),
        migrations.CreateModel(
            name="SocialMediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube")),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social media",
            },
        ),
    ]
