# Generated by Django 5.1.15 on 2026-06-10 00:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "columns",
                    wagtail.fields.StreamField(
                        [("column", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Nagłówek kolumny", "max_length": 80},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Tekst linku", "max_length": 80},
                            ),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Strona (wewnętrzna)", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Adres URL (zewnętrzny)", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Opis (mały tekst pod linkiem)",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 1), ("page", 2), ("url", 3), ("description", 4)]],
                                {},
                            ),
                            6: ("wagtail.blocks.ListBlock", (5,), {"label": "Linki"}),
                            7: ("wagtail.blocks.StructBlock", [[("heading", 0), ("links", 6)]], {}),
                        },
                        help_text="Kolumny linków w stopce.",
                    ),
                ),
                (
                    "newsletter_heading",
                    models.CharField(
                        blank=True,
                        default="Newsletter",
                        max_length=80,
                        verbose_name="Nagłówek newslettera",
                    ),
                ),
                (
                    "newsletter_subtext",
                    models.CharField(
                        blank=True,
                        default="Co miesiąc — bez spamu, sama treść.",
                        max_length=160,
                        verbose_name="Podtekst newslettera",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stopka",
            },
        ),
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "primary_menu",
                    wagtail.fields.StreamField(
                        [("item", 13)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Tekst pozycji", "max_length": 60},
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Strona docelowa", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "URL docelowy (jeśli brak strony)", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "np. 'klaster' — podświetla pozycję na stronach tego działu.",
                                    "label": "Klucz aktywności",
                                    "max_length": 40,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Nagłówek kolumny", "max_length": 80, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Tekst linku", "max_length": 80},
                            ),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Strona (wewnętrzna)", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Adres URL (zewnętrzny)", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Opis (mały tekst pod linkiem)",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 5), ("page", 6), ("url", 7), ("description", 8)]],
                                {},
                            ),
                            10: ("wagtail.blocks.ListBlock", (9,), {"label": "Linki"}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 4), ("links", 10)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.ListBlock",
                                (11,),
                                {"label": "Kolumny dropdownu", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 0),
                                        ("page", 1),
                                        ("url", 2),
                                        ("nav_key", 3),
                                        ("columns", 12),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Pozycje menu głównego, w kolejności od lewej.",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nawigacja (menu główne)",
            },
        ),
        migrations.CreateModel(
            name="PortalsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "portals",
                    wagtail.fields.StreamField(
                        [("portal", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Nazwa portalu", "max_length": 80},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Opis", "max_length": 120, "required": False},
                            ),
                            2: ("wagtail.blocks.URLBlock", (), {"label": "Adres portalu"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("description", 1), ("url", 2)]],
                                {},
                            ),
                        },
                        help_text="Portale logowania (Strefa członka, LMS Akademii, Giełda B2B, Platforma badań).",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portale logowania",
            },
        ),
    ]
