# Generated by Django 5.1.15 on 2026-06-10 00:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_footersettings_navigationsettings_portalssettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="contact_heading",
            field=models.CharField(
                blank=True,
                default="Kontakt",
                max_length=80,
                verbose_name="Nagłówek kolumny kontaktu",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="legal_links",
            field=wagtail.fields.StreamField(
                [("link", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Tekst linku", "max_length": 80}),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Strona (wewnętrzna)", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Adres URL (zewnętrzny)", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "Opis (mały tekst pod linkiem)",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("page", 1), ("url", 2), ("description", 3)]],
                        {},
                    ),
                },
                help_text="Linki prawne w dolnym pasku stopki (RODO, Regulamin, Cookies).",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="portals_heading",
            field=models.CharField(
                blank=True,
                default="Portale",
                max_length=80,
                verbose_name="Nagłówek kolumny portali",
            ),
        ),
    ]
