# Generated by Django 5.1.15 on 2026-06-10 13:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="np. '150+' lub '240 mln zł'",
                        max_length=40,
                        verbose_name="Wartość",
                    ),
                ),
                ("label", models.CharField(max_length=160, verbose_name="Opis")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("home_strip", "Home — pasek pod hero"),
                            ("home_section", "Home — sekcja statystyk"),
                            ("about_klastra", "O klastrze"),
                        ],
                        default="home_strip",
                        max_length=20,
                        verbose_name="Grupa",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Kolejność")),
            ],
            options={
                "verbose_name": "Statystyka",
                "verbose_name_plural": "Statystyki",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(blank=True, max_length=120, verbose_name="Nadtytuł (eyebrow)"),
                ),
                (
                    "headline",
                    wagtail.fields.RichTextField(
                        help_text="Użyj kursywy (em) dla akcentu, jak w mockupie.",
                        verbose_name="Nagłówek",
                    ),
                ),
                ("lead", models.TextField(blank=True, verbose_name="Lead")),
                (
                    "primary_cta_label",
                    models.CharField(blank=True, max_length=60, verbose_name="CTA główne — tekst"),
                ),
                (
                    "primary_cta_url",
                    models.CharField(blank=True, max_length=255, verbose_name="CTA główne — URL"),
                ),
                (
                    "secondary_cta_label",
                    models.CharField(blank=True, max_length=60, verbose_name="CTA drugie — tekst"),
                ),
                (
                    "secondary_cta_url",
                    models.CharField(blank=True, max_length=255, verbose_name="CTA drugie — URL"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tło slajdu.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slajd hero",
                "verbose_name_plural": "Slajdy hero",
            },
        ),
        migrations.CreateModel(
            name="Pillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="np. '01 / FILAR'", max_length=12, verbose_name="Numer"
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Tytuł")),
                ("lead", models.TextField(verbose_name="Opis")),
                ("bullets", models.TextField(blank=True, verbose_name="Punkty (jeden na linię)")),
                (
                    "icon_svg",
                    models.TextField(
                        blank=True,
                        help_text="Wklej kod <svg>…</svg>.",
                        verbose_name="Ikona (inline SVG)",
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(blank=True, max_length=60, verbose_name="Tekst linku"),
                ),
                ("is_dark", models.BooleanField(default=False, verbose_name="Wariant ciemny")),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        help_text="Strona-filar docelowa.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filar",
                "verbose_name_plural": "Filary",
            },
        ),
    ]
