# Generated by Django 5.1.15 on 2026-06-10 13:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PillarPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Nadtytuł (np. 'Filar 01 · Klaster')",
                    ),
                ),
                ("hero_lead", models.TextField(blank=True, verbose_name="Lead w hero")),
                (
                    "primary_cta_label",
                    models.CharField(blank=True, max_length=60, verbose_name="CTA główne — tekst"),
                ),
                (
                    "primary_cta_url",
                    models.CharField(blank=True, max_length=255, verbose_name="CTA główne — URL"),
                ),
                (
                    "secondary_cta_label",
                    models.CharField(blank=True, max_length=60, verbose_name="CTA drugie — tekst"),
                ),
                (
                    "secondary_cta_url",
                    models.CharField(blank=True, max_length=255, verbose_name="CTA drugie — URL"),
                ),
                (
                    "benefits_heading",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Nagłówek sekcji korzyści"
                    ),
                ),
                (
                    "feature_heading",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Blok 'jak działamy' — nagłówek"
                    ),
                ),
                (
                    "feature_lead",
                    models.TextField(blank=True, verbose_name="Blok 'jak działamy' — lead"),
                ),
                (
                    "feature_bullets",
                    models.TextField(
                        blank=True, verbose_name="Blok 'jak działamy' — punkty (jeden na linię)"
                    ),
                ),
                (
                    "steps_heading",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Nagłówek sekcji procesu"
                    ),
                ),
                (
                    "cta_heading",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="CTA strip — nagłówek"
                    ),
                ),
                ("cta_lead", models.TextField(blank=True, verbose_name="CTA strip — lead")),
                (
                    "cta_button_label",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="CTA strip — przycisk"
                    ),
                ),
                (
                    "cta_button_url",
                    models.CharField(blank=True, max_length=255, verbose_name="CTA strip — URL"),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obraz pokazywany przy udostępnianiu na FB/LinkedIn. Zalecane 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Obraz social (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strona filaru",
                "verbose_name_plural": "Strony filarów",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="PillarBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("tag", models.CharField(blank=True, max_length=40, verbose_name="Tag")),
                ("title", models.CharField(max_length=120, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="home.pillarpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PillarStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "number",
                    models.CharField(help_text="np. '01'", max_length=4, verbose_name="Numer"),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="home.pillarpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
