# Generated by Django 5.1.15 on 2026-06-10 13:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_pillarpage_pillarbenefit_pillarstep"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "pillars_eyebrow",
                    models.CharField(blank=True, default="Co robimy", max_length=80),
                ),
                ("pillars_heading", models.CharField(blank=True, max_length=200)),
                ("pillars_lead", models.TextField(blank=True)),
                (
                    "consult_eyebrow",
                    models.CharField(blank=True, default="Bezpłatna konsultacja", max_length=80),
                ),
                ("consult_heading", models.CharField(blank=True, max_length=200)),
                ("consult_lead", models.TextField(blank=True)),
                (
                    "consult_cta_label",
                    models.CharField(blank=True, default="Wyślij zgłoszenie", max_length=60),
                ),
                ("consult_cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "services_eyebrow",
                    models.CharField(blank=True, default="Usługi klastra", max_length=80),
                ),
                ("services_heading", models.CharField(blank=True, max_length=200)),
                (
                    "services_cta_label",
                    models.CharField(blank=True, default="Cała oferta", max_length=60),
                ),
                ("services_cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "members_eyebrow",
                    models.CharField(blank=True, default="Zaufali nam", max_length=80),
                ),
                ("members_heading", models.CharField(blank=True, max_length=200)),
                (
                    "about_eyebrow",
                    models.CharField(blank=True, default="O klastrze", max_length=80),
                ),
                ("about_heading", models.CharField(blank=True, max_length=200)),
                ("about_lead", models.TextField(blank=True)),
                (
                    "about_bullets",
                    models.TextField(blank=True, verbose_name="Punkty (jeden na linię)"),
                ),
                ("about_cta_label", models.CharField(blank=True, max_length=60)),
                ("about_cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "news_eyebrow",
                    models.CharField(blank=True, default="Aktualności", max_length=80),
                ),
                ("news_heading", models.CharField(blank=True, max_length=200)),
                (
                    "news_cta_label",
                    models.CharField(blank=True, default="Wszystkie wpisy", max_length=60),
                ),
                ("news_cta_url", models.CharField(blank=True, max_length=255)),
                (
                    "cta_chip",
                    models.CharField(blank=True, default="Krajowy Klaster Kluczowy", max_length=60),
                ),
                ("cta_heading", models.CharField(blank=True, max_length=200)),
                ("cta_lead", models.TextField(blank=True)),
                ("cta_primary_label", models.CharField(blank=True, max_length=60)),
                ("cta_primary_url", models.CharField(blank=True, max_length=255)),
                ("cta_secondary_label", models.CharField(blank=True, max_length=60)),
                ("cta_secondary_url", models.CharField(blank=True, max_length=255)),
                (
                    "about_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obraz pokazywany przy udostępnianiu na FB/LinkedIn. Zalecane 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Obraz social (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strona główna",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="HomeOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("tag", models.CharField(blank=True, max_length=40, verbose_name="Tag")),
                ("title", models.CharField(max_length=120, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "link_label",
                    models.CharField(
                        blank=True,
                        default="Dowiedz się więcej →",
                        max_length=60,
                        verbose_name="Tekst linku",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=255, verbose_name="URL")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeNewsTeaser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("category", models.CharField(blank=True, max_length=40, verbose_name="Kategoria")),
                (
                    "reading_time",
                    models.CharField(blank=True, max_length=20, verbose_name="Czas czytania"),
                ),
                ("date", models.CharField(blank=True, max_length=20, verbose_name="Data")),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("excerpt", models.TextField(blank=True, verbose_name="Zajawka")),
                ("url", models.CharField(blank=True, max_length=255, verbose_name="URL")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_teasers",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeMemberLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=80, verbose_name="Nazwa")),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_logos",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeHeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="home.heroslide",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_slides",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeConsultStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("text", models.CharField(max_length=200, verbose_name="Krok")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consult_steps",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomePillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_pillars",
                        to="home.homepage",
                    ),
                ),
                (
                    "pillar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="home.pillar",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
