# Generated by Django 5.1.15 on 2026-06-10 00:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("heading", 0), ("paragraph", 1), ("image", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title", "label": "Nagłówek sekcji"},
                            ),
                            1: ("wagtail.blocks.RichTextBlock", (), {"label": "Tekst"}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"label": "Obraz"}),
                        },
                        help_text="Treść dokumentu — nagłówki, akapity, obrazy.",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obraz pokazywany przy udostępnianiu na FB/LinkedIn. Zalecane 1200×630 px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Obraz social (Open Graph)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strona prawna",
                "verbose_name_plural": "Strony prawne",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
